---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: fluentd
    image: eniocarboni/docker-rockylinux-systemd:9
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      fluentd:
        docker_storage_driver: vfs
        # Latest version 17.12.1.ce-1.el7.centos has a bug that prevents
        # testing on travis: https://github.com/docker/for-linux/issues/219
        #docker_version: 17.09.1.ce-1.el7.centos
scenario:
  name: default
verifier:
  name: testinfra
